export const addons = [
  { name: "Multi Bahasa", basic: false, standard: true, premium: true },
  { name: "SEO Dasar", basic: false, standard: false, premium: true },
  { name: "SEO Lanjutan", basic: false, standard: false, premium: false },
  { name: "Integrasi Google Analis", basic: false, standard: true, premium: true },
  { name: "Domain + Hosting Mandiri", basic: false, standard: false, premium: false },
  { name: "Integrasi WhatsApp", basic: false, standard: true, premium: true },
  { name: "Halaman Tambahan (per halaman)", basic: false, standard: false, premium: false },
  { name: "Maintenance (per bulan)", basic: false, standard: false, premium: false },
  { name: "Integrasi Google Maps", basic: false, standard: true, premium: true },
  { name: "Revisi Extra (per revisi minor)", basic: false, standard: false, premium: false },
  { name: "Admin Panel Sederhana", basic: false, standard: false, premium: true },
  { name: "Email Domain", basic: false, standard: false, premium: true },
  { name: "Training Admin Panel", basic: false, standard: false, premium: true },
  { name: "Free Domain (dikelola kova)", basic: false, standard: false, premium: false },
  { name: "Free Hosting (dikelola kova)", basic: false, standard: false, premium: false },
  { name: "Perpanjang domain + Hosting (kelola kova)", basic: false, standard: false, premium: false },
  { name: "custom .com", basic: false, standard: true, premium: true },
  { name: "custom .id", basic: false, standard: false, premium: false },
  { name: "Authentikasi Admin", basic: false, standard: false, premium: false },
];
